version: '3.8'

services:
  db:
    image: mysql:8.1
    container_name: mysql_investimentos
    restart: always
    environment:
      MYSQL_DATABASE: crud_investimentos
      MYSQL_USER: myuser
      MYSQL_PASSWORD: 252722
      MYSQL_ROOT_PASSWORD: verysecret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: